# Generated by Django 4.2 on 2023-04-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_channel_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='host',
        ),
    ]
