# Generated by Django 4.2 on 2023-04-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_post_channel_channel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.channel'),
        ),
    ]
